language: python
python:
  - "2.7"
install:
  - pip install nose
  - pip install mock
  - pip install requests
  - pip install coveralls
script: nosetests --with-coverage --cover-package=messengerbot
after_success:
  coveralls
